### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

### ISSUE THREAD

**Issue by tombackstrom** [ttu/ruuvitag-sensor#121]
Crash on a fresh install, with "ruuvitag -f".
 - OS: Ubuntu 20.04, Python 3.8 through Anaconda3. ruuvitag_sensor-1.1.0

(base) user@machine:~$ alias ruuvitag='python3 anaconda3/lib/python3.8/site-packages/ruuvitag_sensor'
(base) user@machine:~$ ruuvitag -f
Finding RuuviTags. Stop with Ctrl+C.
2021-02-01 09:07:09,606   INFO -                 ruuvi.py: 74 -           find_ruuvitags(): Finding RuuviTags. Stop with Ctrl+C.
Start receiving broadcasts (device 0)
2021-02-01 09:07:09,629   INFO -                bleson.py: 59 -                    start(): Start receiving broadcasts (device 0)
Process Process-3:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/ruuvitag_sensor/adapters/bleson.py", line 19, in _run_get_data_background
    (observer, q) = BleCommunicationBleson.start(bt_device)
  File "/home/user/anaconda3/lib/python3.8/site-packages/ruuvitag_sensor/adapters/bleson.py", line 63, in start
    adapter = get_provider().get_adapter(int(bt_device))
  File "/home/user/anaconda3/lib/python3.8/site-packages/bleson/providers/linux/linux_provider.py", line 10, in get_adapter
    adapter.open()
  File "/home/user/anaconda3/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 31, in open
    self._socket = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_RAW, socket.BTPROTO_HCI)
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

Background information

(base) user@machine:~$ ruuvitag --help
usage: ruuvitag_sensor [-h] [-g MAC_ADDRESS] [-d BT_DEVICE] [-f] [-l] [-s] [--version]

optional arguments:
  -h, --help            show this help message and exit
  -g MAC_ADDRESS, --get MAC_ADDRESS
                        Get data
  -d BT_DEVICE, --device BT_DEVICE
                        Set Bluetooth device id (default hci0)
  -f, --find            Find broadcasting RuuviTags
  -l, --latest          Get latest data for found RuuviTags
  -s, --stream          Stream broadcasts from all RuuviTags
  --version             show program's version number and exit
(base) user@machine:~$ ruuvitag --version
ruuvitag_sensor 1.1.0

**Comment by ttu** [comment]
Hi! It is possible that the Python installed with Anaconda is not compiled with Bluetooth. Try installing a different version or try with the default version that comes with Ubuntu.
