### ISSUE TITLE
ruuvi_tag sensor only runs as root on raspbian?

### ISSUE THREAD

**Issue by wimdk2020** [ttu/ruuvitag-sensor#62]
Ruuvitag gives and error when not running as root:
python3 /root/.local/lib/python3.4/site-packages/ruuvitag_sensor --help
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.4/site-packages/ruuvitag_sensor/__main__.py", line 4, in <module>
    import ruuvitag_sensor
ImportError: No module named 'ruuvitag_sensor'

**Comment by wimdk2020** [comment]
solved by installing with --user
